name: Docker Image CI

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:

            - name: Lowercase username
              run: echo "LOWERCASE_USERNAME=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/amd64,linux/arm64
                  push: true
                  sbom: true
                  tags: |
                      ${{ secrets.DOCKER_USERNAME }}/caddy-tailscale:latest
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Push image to GHCR
              run: |
                docker buildx imagetools create --tag ghcr.io/${{ env.LOWERCASE_USERNAME }}/caddy-tailscale:latest ${{ secrets.DOCKER_USERNAME }}/caddy-tailscale:latest